Debugging collectstatic

diff --git a/bin/steps/django/collectstatic b/bin/steps/django/collectstatic
--- a/bin/steps/django/collectstatic
+++ b/bin/steps/django/collectstatic
@@ -1,29 +1,17 @@
 #!/usr/bin/env bash
 
-puts-step "steps/django/collectstatic"
 set +e
 
-# Syntax sugar.
-indent() {
-  RE="s/^/       /"
-  [ $(uname) == "Darwin" ] && sed -l "$RE" || sed -u "$RE"
-}
-
-
 # Check if collectstatic is configured properly.
-python $MANAGE_FILE collectstatic --dry-run --noinput &> /dev/null && RUN_COLLECTSTATIC=true
+python $MANAGE_FILE collectstatic --dry-run --noinput
 
 # Compile assets if collectstatic appears to be kosher.
-if [ "$RUN_COLLECTSTATIC" ]; then
+# if [ "$RUN_COLLECTSTATIC" ]; then
+puts-step "Collecting static files"
+python $MANAGE_FILE collectstatic --noinput  2>&1 | sed '/^Copying/d;/^$/d;/^ /d' | indent
 
-    echo "-----> Collecting static files"
-    python $MANAGE_FILE collectstatic --noinput  2>&1 | sed '/^Copying/d;/^$/d;/^ /d' | indent
-
-    [ $? -ne 0 ] && {
-        echo " !     Error running manage.py collectstatic. More info:"
-        echo "       http://devcenter.heroku.com/articles/django-assets"
-    }
-fi
-
-echo
-
+[ $? -ne 0 ] && {
+  puts-warn "Error running manage.py collectstatic. More info:"
+  echo "http://devcenter.heroku.com/articles/django-assets" | indent
+}
+# fi
